import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        {children}{" "}
        <div className="fixed bottom-0 right-0">
          <p>
            Schedule a Meeting <span>powered by Calendly</span>
          </p>
        </div>
      </body>
    </html>
  );
}
